version: "3.8"
services:
  redis:
    image: redis:latest
    networks:
      - flirtex-network

  api:
    image: flirtex.registry.jetbrains.space/p/connecta/containers/api:latest
    deploy:
      update_config:
        order: stop-first
        failure_action: rollback
        delay: 10s
    depends_on:
      - redis
    volumes:
      - /var/run/postgresql:/var/run/postgresql
      - /usr/local/src/flirtex/api:/api
    networks:
      - flirtex-network

networks:
  flirtex-network:
    driver: bridge
