version: "3.8"
services:
  redis:
    image: redis:latest
    networks:
      - flirtex-network

  api:
    build:
      context: ./api
      dockerfile: ./docker/Dockerfile
    environment:
      - WORKERS_COUNT=${WORKERS_COUNT}
      - BOT_TOKEN=${BOT_TOKEN}
      - JWT_SECRET=${JWT_SECRET}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - DATABASE_URI=${DATABASE_URI}
      - SENTRY_DSN=${SENTRY_DSN}
      - JWT_ACCESS_TOKEN_EXPIRE_SECONDS=${JWT_ACCESS_TOKEN_EXPIRE_SECONDS}
      - JWT_REFRESH_TOKEN_EXPIRE_SECONDS=${JWT_REFRESH_TOKEN_EXPIRE_SECONDS}
      - REDIS_NOTIFIER_URL=${REDIS_NOTIFIER_URL}
      - S3_PHOTO_BUCKET_NAME=${S3_PHOTO_BUCKET_NAME}
    depends_on:
      - redis
    volumes:
      - /var/run/postgresql:/var/run/postgresql
      - /usr/local/src/flirtex/api:/api
      - /usr/local/src/flirtex/api/.venv:/opt/pysetup/.venv
    networks:
      - flirtex-network

networks:
  flirtex-network:
    driver: bridge
