version: "2.1"
services:
  pg-db:
    build:
      context: ./pg-db
      dockerfile: ./docker/Dockerfile  # Путь к вашему Dockerfile для PostgreSQL с PostGIS
    hostname: db
    env_file:
      - ./pg-db/docker/.env
    volumes:
      - ./pg-db/data:/var/lib/postgresql/data  # Том для хранения данных
    networks:
      - flirtex-network
    restart: always

  redis:
    image: redis:latest
    networks:
      - flirtex-network

  api:
    build:
      context: ./api
      dockerfile: ./docker/Dockerfile
    depends_on:
      - pg-db
      - redis
    env_file:
      - ./api/docker/.env
    volumes:
      - ./api:/api
    networks:
      - flirtex-network

networks:
  flirtex-network:
    driver: bridge


