version: "2.1"
services:
  pg-db:
    build:
      context: ./pg-db
      dockerfile: ./docker/Dockerfile  # Путь к вашему Dockerfile для PostgreSQL с PostGIS
    hostname: db
    env_file:
      - ./pg-db/docker/.env
    volumes:
      - ./pg-db/data:/var/lib/postgresql/data  # Том для хранения данных
    ports:
      - 5432:5432  # Проброс порта (если требуется доступ с хост-машины)
    networks:
      - flirtex-network
    restart: always

  redis:
    image: redis:latest
    networks:
      - flirtex-network
    ports:
      - 6379:6379

  api:
    build:
      context: ./api
      dockerfile: ./docker/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - rabbitmq
      - pg-db
      - redis
    env_file:
      - ./api/docker/.env
    volumes:
      - ./api:/api
    networks:
      - flirtex-network
        
  notifier:
    build:
      context: ./notifier
      dockerfile: ./docker/Dockerfile
    ports:
      - 8081:8081
    depends_on:
      - api
    env_file:
      - ./notifier/docker/.env
    volumes:
      - ./notifier:/notifier
    networks:
      - flirtex-network

  nginx:
    image: nginx:stable
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
      - notifier
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt

networks:
  flirtex-network:
    driver: bridge


