version: "3.8"
services:
  redis:
    image: redis:latest
    networks:
      - flirtex-network

  api:
    build:
      context: ./api
      dockerfile: ./docker/Dockerfile
    deploy:
      update_config:
        order: stop-first
        failure_action: rollback
        delay: 10s
    depends_on:
      - redis
    volumes:
      - /var/run/postgresql:/var/run/postgresql
      - /usr/local/src/flirtex/api:/api
      - /usr/local/src/flirtex/env/api/.venv:/opt/pysetup/.venv
    networks:
      - flirtex-network

networks:
  flirtex-network:
    driver: bridge
