version: "3.8"
services:
  redis:
    image: redis:latest
    networks:
      - flirtex-network

  api:
    hostname: api
    build:
      context: ./api
      dockerfile: ./docker/Dockerfile
      args:
        WORKER_COUNT: ${WORKER_COUNT}
    env_file:
      - ./.secrets/api/.env
    volumes:
      - /tmp/api:/tmp/api
    depends_on:
      - redis
    networks:
      - flirtex-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  bot:
    hostname: bot
    build:
      context: ./tg-bot
      dockerfile: ./docker/Dockerfile
    env_file:
      - ./.secrets/bot/.env
    networks:
      - flirtex-network

  nginx:
    build:
      context: ./nginx
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /usr/local/src/flirtex/webapp:/var/www/app/public
      - /etc/letsencrypt:/etc/letsencrypt
      - /tmp/api:/tmp/api
      - type: bind
        source: /usr/local/src/flirtex/nginx/src/nginx.conf
        target: /etc/nginx/nginx.conf
    networks:
      - flirtex-network

networks:
  flirtex-network:
    driver: bridge
