version: "3.8"
services:
  redis:
    image: redis:latest
    networks:
      - flirtex-network

  api:
    build:
      context: ./api
      dockerfile: ./docker/Dockerfile
      args:
        WORKER_COUNT: ${WORKER_COUNT}
    env_file:
      - ./.secrets/api/.env
    depends_on:
      - redis
    networks:
      - flirtex-network
    extra_hosts:
      - "db:172.17.0.1"
networks:
  flirtex-network:
    driver: bridge
