"""

Revision ID: 9e8cf60df46e
Revises: 
Create Date: 2023-05-24 19:06:30.682238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9e8cf60df46e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "profile", "is_active", existing_type=sa.BOOLEAN(), nullable=False, schema="core"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "profile", "is_active", existing_type=sa.BOOLEAN(), nullable=True, schema="core"
    )
    # ### end Alembic commands ###
