FROM python:3.11.2-slim-buster

RUN apt-get update && apt-get install -y --no-install-recommends \
    # Needed for fetching stuff
    ca-certificates \
    wget gnupg \
    && rm -rf /var/lib/apt/lists/* \
    
RUN pip install poetry
RUN mkdir -p /app
COPY . /app

WORKDIR /app

RUN poetry install
CMD ["poetry", "run", "python", "-m", "app.main"]
